name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-24.04
    env:
      PDK_ROOT: '/home/runner/pdk'
      PDK: gf180mcuD
      PDK_VERSION: 0fe599b2afb6708d281543108caf8310912f54af
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        shell: bash
        run: pip install -r requirements.txt

      - name: Install gf180mcu PDK
        uses: TinyTapeout/ciel-action@v1
        with:
          pdk_name: ${{ env.PDK }}
          pdk_version: ${{ env.PDK_VERSION }}
          pdk_root: ${{ env.PDK_ROOT }}

      - name: Run tests
        run: |
          make
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: 'results.xml'
        if: always()

      - name: upload waveform and test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            tb.vcd
            results.xml
